src/Entity/Rent.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use App\Repository\RentRepository;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=RentRepository::class)
 */
class Rent
{
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Length(min=5, max=255)
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @Assert\Regex("/^[0-9]{5}$/")
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $available = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @var PictureAppartementA|null
     */
    private $picture;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PictureRent", mappedBy="rent", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;

    /**
     * @Assert\All({
     *   @Assert\Image(mimeTypes="image/jpeg")
     * })
     */
    private $pictureFiles;

    /**
     * @ORM\Column(type="float", scale=4, precision=6)
     */
    private $lat;

    /**
     * @ORM\Column(type="float", scale=4, precision=7)
     */
    private $lng;

     /**
     * @ORM\ManyToMany(targetEntity="App\Entity\OptionRent", inversedBy="rent")
     */
    private $options;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $createdBy;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->updated_at = new \DateTime();
        $this->options = new ArrayCollection();
        $this->pictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }


    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getAvailable(): ?bool
    {
        return $this->available;
    }

    public function setAvailable(bool $available): self
    {
        $this->available = $available;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|PictureRent[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function getPicture(): ?PictureRent
    {
        return $this->picture;
    }

    public function setPicture(PictureRent $picture): self
    {
        $this->picture = $picture;
        return $this;
    }

    public function addPicture(PictureRent $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setRent($this);
        }

        return $this;
    }

    public function removePicture(PictureRent $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getRent() === $this) {
                $picture->setRent(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPictureFiles()
    {
        return $this->pictureFiles;
    }

    /**
     * @param mixed $pictureFiles
     * @return Rent
     */
    public function setPictureFiles($pictureFiles): self
    {
        foreach($pictureFiles as $pictureFile) {
            $picture = new PictureRent();
            $picture->setImageFile($pictureFile);
            $this->addPicture($picture);
        }
        $this->pictureFiles = $pictureFiles;
        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getLat(): ?int
    {
        return $this->lat;
    }

    public function setLat(int $lat): self
    {
        $this->lat = $lat;

        return $this;
    }

    public function getLng(): ?int
    {
        return $this->lng;
    }

    public function setLng(int $lng): self
    {
        $this->lng = $lng;

        return $this;
    }

        /**
     * @return Collection|OptionRent[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(OptionRent $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addRent($this);
        }

        return $this;
    }

    public function removeOption(OptionRent $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeRent($this);
        }

        return $this;
    }

    public function getCreatedBy(): ?string
    {
        return $this->createdBy;
    }

    public function setCreatedBy(string $createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }
}

src/Form/RentType.php
<?php

namespace App\Form;

use App\Entity\OptionRent;
use App\Entity\Rent;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('content')
            ->add('surface')
            ->add('createdBy', HiddenType::class)
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('options', EntityType::class, [
                'class' => OptionRent::class,
                'required' => false,
                'choice_label' => 'name',
                'multiple' => true
            ])
            ->add('pictureFiles', FileType::class, [
                'required' => false,
                'multiple' => true
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code', IntegerType::class)
            ->add('lat', HiddenType::class)
            ->add('lng', HiddenType::class)
            ->add('available')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Rent::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices()
    {
        $choices = Rent::HEAT;
        $output = [];
        foreach($choices as $k => $v)
        {
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/RentController.php
<?php 

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Mailbox;
use App\Entity\Rent;
use App\Entity\RentSearch;
use App\Form\ContactType;
use App\Form\MailboxType;
use App\Form\RentSearchType;
use App\Notification\ContactNotification2;
use App\Repository\RentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class RentController extends AbstractController
{

    private $repository;

    /**
     * @var RentRepository
     * @var EntityManagerInterface
     */

    public function __construct(RentRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route("/louer", name="rent.index")
     * @return Responce
    */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $search = new RentSearch();
        $form = $this->createForm(RentSearchType::class, $search);
        $form->handleRequest($request);
        return $this->render('rent/index.html.twig', [
            'current_menu2' => 'rents',
            'rent' => $this->repository->paginateAllVisible($search, $request->query->getInt('page', 1)),
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/louer/{slug}:{id}", name="rent.show") requirements={"slug": [a-z0-9\-]""}
     * @param Rent $rent
     * @return Response
     */
    public function show(Rent $rent, string $slug, Request $request): Response
    {
        if($rent->getSlug() !== $slug){
            return $this->redirectToRoute('rent.show', [
                'id' => $rent->getId(),
                'slug' => $rent->getSlug()
            ], 301);
        }

        $mailbox = new Mailbox();
        $form = $this->createForm(MailboxType::class, $mailbox);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {

            $title = $rent->getTitle($mailbox, $rent->getTitle());
            $mailbox->setSubject($title);
            $mailbox->setCategorie('1');
            $this->em->persist($mailbox);
            $this->em->flush();
            $this->addFlash('success', 'Votre message a bien été envoyé');
            return $this->redirectToRoute('rent.show', [
                'id' => $rent->getId(),
                'slug' => $rent->getSlug() 
            ]);
        }

        return $this->render('rent/show.html.twig', [
            'rent' => $rent,
            'available' => $rent->getAvailable(),
            'current_menu2' => 'rent',
            'form' => $form->createView()
        ]);
    }

}

?>

templates/rent/_rent.html.twig
<div class="card card-per shadow-sm">
  {% if rents.picture %}
    <div style="background: url('{{ vich_uploader_asset(rents.picture, 'imageFile') }}'); background-position: center; width: 100%; height:210px;"></div>
    {% else %}
      <img src="{{ '/images/empty.jpg' }}" alt="card-img-top" style="width: 100%; height:auto;">
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">
      <a href="{{ path('rent.show', {slug: rents.slug, id: rents.id}) }}">
        {{ rents.title }}
      </a>
    </h5>
    <p class="card-text">{{ rents.surface }} m² - {{ rents.city }} ({{ rents.postalCode }})</p>
    <p>Mise en ligne par {{ rents.createdBy }}</p>
    <p>{% if rents.available == 0 %}<i class="fas fa-check text-success"></i> Disponible{% else %}<i class="fas fa-times text-danger"></i> Louer{% endif %}</p>
    <div class="text-success card-foot mb-3">
      {{ rents.formattedPrice }} €
    </div>
    <div class="d-flex justify-content-between align-items-center mt-2">
      <div class="btn-group">
        <a href="{{ path('rent.show', {slug: rents.slug, id: rents.id}) }}" class="btn btn-outline-info nav-link text-black text-bold">Voir le bien</a>
      </div>
    </div>
  </div>
</div>

templates/rent/index.html.twig
{% extends "base.html.twig" %}

{% block title globals.title ~ ' Toutes nos locations' %}

{% block body %}

        <div class="container w-50">

        <p class="title-cont">Affiner les résultats : </p>

        <hr class="mb-4" />
        
        {{ form_start(form) }}
        <div style="display: flex; justify-content: center;">
            <div class="form-row">
                <div class="col-4">
                    {{ form_row(form.minSurface) }}
                </div>
                <div class="col-4">
                    {{ form_row(form.maxPrice) }}
                </div>
                <div class="col-4">
                    {{ form_row(form.options) }}
                </div>
            </div>
        </div>
        <div style="display: flex; justify-content: center;">
            <div class="form-row">
                <div class="col-9 m-auto">
                    {{ form_row(form.address, {'id': 'search_address'}) }}
                </div>
                <div class="col-md-12">
                    <div class="form-group text-center range">
                        {{ form_row(form.distance) }}
                    </div>  
                </div>
                <div class="col">
                    <div class="form-group text-center">
                        <button class="button-submit">Rechercher</button>
                    </div>
                </div>
            </div>
        </div>
        {{ form_end(form) }}

            <hr/>

        </div>

    <div class="container mt-4">  

        <p class="title-cont">Voir toutes nos locations</p>

        <hr/>

        <div class="row">
            {% for rents in rent %}
            <div class="col-md-4 mb-4">
                {% include 'rent/_rent.html.twig' %}
            </div>
            {% endfor %}
        </div>

        <hr/>

        <div class="row mt-4">
            <div class="col-12 col-md-12 col-xl-12" style="display: flex;justify-content: space-around;">
                {{ knp_pagination_render(rent) }}
            </div>
        </div>
    </div>    
{% endblock %}

templates/rent/show.html.twig
{% extends 'base.html.twig' %}

{% block title globals.title ~ ' ' ~ rent.title %}
{% block description '' ~ rent.content %}
{% block url '' ~ path('rent.show', {slug: rent.slug, id: rent.id}) %}
{% block url2 '' ~ path('rent.show', {slug: rent.slug, id: rent.id}) %}
{% block title2 globals.title ~ ' - ' ~ rent.title %}
{% block title3 globals.title ~ ' - ' ~ rent.title %}
{% block description2 '' ~ rent.content %}
{% block description3 '' ~ rent.content %}

{% block stylesheets %}

<style>
	.jumbotron {
		margin: 0 auto !important;
	}
</style>

{% endblock %}

{% block body %}

	<div class="jumbotron pt-3 pb-3">
		<div class="container">

			{% for message in app.flashes('success') %}
				<div class="alert alert-success text-center w-25 m-auto mb-3">
					<i class="fa fa-check text-success" aria-hidden="true"></i> {{ message }}
				</div>
			{% endfor %}

			{% if not form.vars.valid %}
				<div class="alert alert-danger text-center w-25 m-auto mb-3">
					<i class="fas fa-times text-danger" aria-hidden="true"></i> Une erreur est survenue !
				</div>
			{% endif %}

			<div class="row" style="justify-content: center;">
				<div class="col-md-7">
					<div data-slider>
						{% if rent.pictures is empty %}
							<img src="{{ '/images/empty.jpg' }}" alt="card-img-top" style="width: 100%; height:auto;">
						{% else %}
							{% for picture in rent.pictures %}
								<img src="{{ vich_uploader_asset(picture, 'imageFile') }}"  style="width: 100%; height:auto;" />
							{% endfor %}
						{% endif %}
					</div>
				</div>
				<div class="col-md-4 ml-4 mr-4 col-4 col-sm-4">
					<h3>{{ rent.title }}</h3>
					<h6>Mise en ligne par {{ rent.createdBy }}</h6>
					<h5>{{ rent.rooms }}
						pièces -
						{{ rent.surface }}
						m²</h5>
					<h6>{% if available == 0 %}<i class="fas fa-check text-success"></i> Disponible{% else %}<i class="fas fa-times text-danger"></i> Louer{% endif %}</h6>
					<div class="text-success" style="font-size: 2rem;font-weight: bold;">{{ rent.formattedPrice }}
						€</div>
					<a href="#" class="btn btn-primary" id="contactButton" {% if form.vars.submitted %} style="display: none;" {% endif %}>Contacter l'agence</a>
					<div id="contactForm" class="mt-4" {% if not form.vars.submitted %} style="display: none;" {% endif %}>
						{{ form_start(form, {'attr': {'id': 'captcha'}}) }}
						<div class="row">
							<div class="col">{{ form_row(form.firstname) }}</div>
							<div class="col">{{ form_row(form.lastname) }}</div>
						</div>
						<div class="row">
							<div class="col">{{ form_row(form.phone) }}</div>
							<div class="col">{{ form_row(form.email) }}</div>
						</div>
						{{ form_rest(form) }}
						<script src="https://www.google.com/recaptcha/api.js"></script>
						<script>
							function onSubmit2(token) {
                document.getElementById("captcha").submit();
              }
						</script>
						<button class="btn btn-primary g-recaptcha" data-sitekey="6Lcwj5MaAAAAACDE4Nd4kYXFmK7FprQAHzf5xjvW" data-callback='onSubmit2' data-action='submit'>Envoyer</button>
						{{ form_end(form) }}
            
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="container mt-4 mb-4">

	<hr />

		<p>
			{{ rent.content | nl2br }}
		</p>

	<hr />

		<div class="row">
			<div class="col-md-8">
				<h2>Caractéristiques</h2>
				<table class="table table-striped">
					<tr>
						<td>Surface habitable</td>
						<td>{{ rent.surface }}
							m²</td>
					</tr>
					<tr>
						<td>Pièces</td>
						<td>{{ rent.rooms }}</td>
					</tr>
					<tr>
						<td>Chambres</td>
						<td>{{ rent.bedrooms }}</td>
					</tr>
					<tr>
						<td>Etage</td>
						<td>{{ rent.floor }}</td>
					</tr>
					<tr>
						<td>Chauffage</td>
						<td>{{ rent.heatType }}</td>
					</tr>
				</table>
			</div>
			<div class="col-md-4">
				<h2>Spécificités</h2>
				<ul class="list-group">
					{% for option in rent.options %}
						<li class="list-group-item">{{ option.name }}</li>
					{% endfor %}
				</ul>
			</div>
			<hr />
		</div>
		<div id="map" style="width: 100%; height: 400px" data-lat="{{ rent.lat }}" data-lng="{{ rent.lng }}"></div>
	</div>
{% endblock %}