src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=BlogRepository::class)
 */
class Blog
{
    const CAT = [
        0 => 'Actualités presse',
        1 => 'Location',
        2 => 'Gestion',
        3 => 'Syndic',
        4 => 'Vente',
        5 => 'Immobilières',
        6 => 'Infos',
        7 => 'Immoblier neuf',
    ];

    const DRAFT = [
        0 => 'Brouillon',
        1 => 'En ligne',
    ];
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=135)
     */
    private $smallContent;

    /**
     * @ORM\Column(type="text")
     */
    private $largeContent;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="integer")
     */
    private $categorie;

    /**
     * @ORM\Column(type="integer")
     */
    private $roughDraft;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @var PictureBlog|null
     */
    private $picture;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PictureBlog", mappedBy="blog", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;

    /**
     * @Assert\All({
     *   @Assert\Image(mimeTypes="image/jpeg")
     * })
     */
    private $pictureFiles;

    public function __construct()
     {
         $this->categorie = 0;
         $this->author = null;
         $this->createdAt = new \DateTime();
         $this->roughDraft = 0;
         $this->updated_at = new \DateTime();
         $this->pictures = new ArrayCollection();
     }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSmallContent(): ?string
    {
        return $this->smallContent;
    }

    public function setSmallContent(string $smallContent): self
    {
        $this->smallContent = $smallContent;

        return $this;
    }

    public function getLargeContent(): ?string
    {
        return $this->largeContent;
    }

    public function setLargeContent(string $largeContent): self
    {
        $this->largeContent = $largeContent;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCategorie(): ?int
    {
        return $this->categorie;
    }

    public function setCategorie(int $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getCatType(): string
    {
        return self::CAT[$this->categorie];
    }

    public function getRoughDraft(): ?int
    {
        return $this->roughDraft;
    }

    public function setRoughDraft(int $roughDraft): self
    {
        $this->roughDraft = $roughDraft;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection|PictureBlog[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function getPicture(): ?PictureBlog
    {
        return $this->picture;
    }

    public function setPicture(PictureBlog $picture): self
    {
        $this->picture = $picture;
        return $this;
    }

    public function addPicture(PictureBlog $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setBlog($this);
        }

        return $this;
    }

    public function removePicture(PictureBlog $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getBlog() === $this) {
                $picture->setBlog(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPictureFiles()
    {
        return $this->pictureFiles;
    }

    /**
     * @param mixed $pictureFiles
     * @return Blog
     */
    public function setPictureFiles($pictureFiles): self
    {
        foreach($pictureFiles as $pictureFile) {
            $picture = new PictureBlog();
            $picture->setImageFile($pictureFile);
            $this->addPicture($picture);
        }
        $this->pictureFiles = $pictureFiles;
        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

}

src/Entity/Rent.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use App\Repository\RentRepository;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=RentRepository::class)
 */
class Rent
{
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Length(min=5, max=255)
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @Assert\Regex("/^[0-9]{5}$/")
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $available = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @var PictureAppartementA|null
     */
    private $picture;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PictureRent", mappedBy="rent", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;

    /**
     * @Assert\All({
     *   @Assert\Image(mimeTypes="image/jpeg")
     * })
     */
    private $pictureFiles;

    /**
     * @ORM\Column(type="float", scale=4, precision=6)
     */
    private $lat;

    /**
     * @ORM\Column(type="float", scale=4, precision=7)
     */
    private $lng;

     /**
     * @ORM\ManyToMany(targetEntity="App\Entity\OptionRent", inversedBy="rent")
     */
    private $options;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $createdBy;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->updated_at = new \DateTime();
        $this->options = new ArrayCollection();
        $this->pictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }


    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getAvailable(): ?bool
    {
        return $this->available;
    }

    public function setAvailable(bool $available): self
    {
        $this->available = $available;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|PictureRent[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function getPicture(): ?PictureRent
    {
        return $this->picture;
    }

    public function setPicture(PictureRent $picture): self
    {
        $this->picture = $picture;
        return $this;
    }

    public function addPicture(PictureRent $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setRent($this);
        }

        return $this;
    }

    public function removePicture(PictureRent $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getRent() === $this) {
                $picture->setRent(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPictureFiles()
    {
        return $this->pictureFiles;
    }

    /**
     * @param mixed $pictureFiles
     * @return Rent
     */
    public function setPictureFiles($pictureFiles): self
    {
        foreach($pictureFiles as $pictureFile) {
            $picture = new PictureRent();
            $picture->setImageFile($pictureFile);
            $this->addPicture($picture);
        }
        $this->pictureFiles = $pictureFiles;
        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getLat(): ?int
    {
        return $this->lat;
    }

    public function setLat(int $lat): self
    {
        $this->lat = $lat;

        return $this;
    }

    public function getLng(): ?int
    {
        return $this->lng;
    }

    public function setLng(int $lng): self
    {
        $this->lng = $lng;

        return $this;
    }

        /**
     * @return Collection|OptionRent[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(OptionRent $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addRent($this);
        }

        return $this;
    }

    public function removeOption(OptionRent $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeRent($this);
        }

        return $this;
    }

    public function getCreatedBy(): ?string
    {
        return $this->createdBy;
    }

    public function setCreatedBy(string $createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }
}

templates/user/public.html.twig
{% extends "base.html.twig" %}

{% block title globals.title ~ ' Profil de ' ~ user.username %}
{% block description '' ~ user.biography %}
{% block url '' ~ path('user.public', { username: user.username }) %}
{% block url2 '' ~ path('user.public', { username: user.username }) %}
{% block title2 globals.title ~ ' Profil de ' ~ user.username %}
{% block title3 globals.title ~ ' Profil de ' ~ user.username %}
{% block description2 '' ~ user.biography %}
{% block description3 '' ~ user.biography %}

{% block body %}

<style>
.card {
    box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
}

.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0,0,0,.125);
    border-radius: .25rem;
}

.card-body {
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1rem;
}

.gutters-sm {
    margin-right: -8px;
    margin-left: -8px;
}

.gutters-sm>.col, .gutters-sm>[class*=col-] {
    padding-right: 8px;
    padding-left: 8px;
}
.mb-3, .my-3 {
    margin-bottom: 1rem!important;
}

.bg-gray-300 {
    background-color: #e2e8f0;
}
.h-100 {
    height: 100%!important;
}
.shadow-none {
    box-shadow: none!important;
}
</style>

<div class="container mt-4 mb-4">
    <div class="main-body">
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">

                    {% if user.pictures is empty %}
                      <img src="{{ '/images/default_profil.png' }}" alt="{{ user.username }}" class="rounded-circle" width="150" />
                    {% else %}
                      {% for picture in user.pictures %}
                        <img src="{{ vich_uploader_asset(picture, 'imageFile') }}" alt="{{ user.username }}" class="rounded-circle" width="150" />
                      {% endfor %}
                    {% endif %}
                  
                    <div class="mt-3">
                      <h4>{{ user.username }}</h4>
                      {% for role in user.roles %}
                            {% if role == "ROLE_USER" %}
                                <p class="text-secondary mb-1">Utilisateur</p>
                            {% elseif role == "ROLE_PRO" %}
                                <p class="text-secondary mb-1">Professionnel</p>
                            {% elseif role == "ROLE_SUPER_ADMIN" %}
                                <p class="text-secondary mb-1">Administrateur</p>
                            {% endif %}
                        {% endfor %}
                      <p class="text-muted font-size-sm">{{ user.city}}, {{ user.postalCode}}</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card mt-3">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Site internet</h6>
                    <span class="text-secondary"><a class="text-secondary" href="{{ user.link }}" target="_blank">{{ user.link }}</a></span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter mr-2 icon-inline text-info"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>Twitter</h6>
                    <span class="text-secondary"><a class="text-secondary" href="https://twitter.com/{{ user.twitter }}" target="_blank">{{ user.twitter }}</a></span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram mr-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h6>
                    <span class="text-secondary"><a class="text-secondary" href="https://www.instagram.com/{{ user.instagram }}/?hl=fr/" target="_blank">{{ user.instagram }}</a></span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook mr-2 icon-inline text-primary"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>Facebook</h6>
                    <span class="text-secondary"><a class="text-secondary" href="https://fr-fr.facebook.com/{{ user.facebook }}" target="_blank">{{ user.facebook }}</a></span>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Adresse email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user.email }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Téléphone</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user.phone }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Mobile</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      0{{ user.mobile }}
                    </div>
                  </div>
                </div>
              </div>
              <div class="row gutters-sm">


                <div class="col-sm-6 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">Les actualiés</i></h6>
              
                      {% for blog in blogs %}
                      <small class="text-uppercase font-weight-bold"><a href="{{ path('blog.show', {id: blog.id}) }}" target="_blank">{{ blog.title }}</a></small>
                      <div class="mb-0">
                        <p class="mb-0"><i class="fas fa-pencil-alt mr-2"></i>Publié le {{ blog.createdAt|format_datetime() }}</p>
                        <p class="mb-0">{% if blog.updatedAt != null %}Modifié le {{ blog.updatedAt|format_datetime() }} {% else %} L'article n'a pas été modifié {% endif %}</p>
                        <p><i class="fas fa-caret-right text-primary pr-1"></i>{{ blog.catType }}</p>
                      </div>
                      <hr>
                      {% endfor %}
                    </div>
                  </div>
                </div>


                <div class="col-sm-6 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">Les biens</i></h6>
                      
                      {% for property in properties %}
                      <small class="text-uppercase font-weight-bold"><a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}" target="_blank">{{ property.title }}</a></small>
                      <div class="mb-0">
                        <p class="mb-0">{% if property.sold == 0 %}<i class="fas fa-check text-success"></i> <span class="font-weight-bold">Disponible</span>{% else %}<i class="fas fa-times text-danger"></i> <span class="font-weight-bold">Vendu</span>{% endif %} | Prix : <span class="font-weight-bold">{{ property.formattedPrice }}</span> <i class="fas fa-euro-sign text-danger"></i></p>
                        <p class="mb-0">{{ property.address }} - {{ property.postalCode}}</p>
                        <p><i class="fas fa-map-marker-alt text-primary"></i> {{ property.city }}</p>
                      </div>
                      <hr>
                      {% endfor %}

                    </div>
                  </div>
                </div>
                <div class="col-sm-6 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">Les locations</i></h6>
              
                      {% for rent in rents %}
                      <small class="text-uppercase font-weight-bold"><a href="{{ path('rent.show', {slug: rent.slug, id: rent.id}) }}" target="_blank">{{ rent.title }}</a></small>
                      <div class="mb-0">
                        <p class="mb-0">{% if rent.available == 0 %}<i class="fas fa-check text-success"></i> <span class="font-weight-bold">Disponible</span>{% else %}<i class="fas fa-times text-danger"></i> <span class="font-weight-bold">Vendu</span>{% endif %} | Prix : <span class="font-weight-bold">{{ rent.formattedPrice }}</span> <i class="fas fa-euro-sign text-danger"></i></p>
                        <p class="mb-0">{{ rent.address }} - {{ rent.postalCode}}</p>
                        <p><i class="fas fa-map-marker-alt text-primary"></i> {{ rent.city }}</p>
                      </div>
                      <hr>
                      {% endfor %}
                    </div>
                  </div>
                </div>

                <div class="col-sm-6 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">Les appartements (en ventes)</i></h6>
              
                      {% for appartementA in appartementAs %}
                      <small class="text-uppercase font-weight-bold"><a href="{{ path('appartementA.show', {slug: appartementA.slug, id: appartementA.id}) }}" target="_blank">{{ appartementA.title }}</a></small>
                      <div class="mb-0">
                        <p class="mb-0">{% if appartementA.sold == 0 %}<i class="fas fa-check text-success"></i> <span class="font-weight-bold">Disponible</span>{% else %}<i class="fas fa-times text-danger"></i> <span class="font-weight-bold">Vendu</span>{% endif %} | Prix : <span class="font-weight-bold">{{ appartementA.formattedPrice }}</span> <i class="fas fa-euro-sign text-danger"></i></p>
                        <p class="mb-0">{{ appartementA.address }} - {{ appartementA.postalCode}}</p>
                        <p><i class="fas fa-map-marker-alt text-primary"></i> {{ appartementA.city }}</p>
                      </div>
                      <hr>
                      {% endfor %}
                    </div>
                  </div>
                </div>

                <div class="col-sm-6 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">Les appartements (en ventes)</i></h6>
              
                      {% for appartementB in appartementBs %}
                      <small class="text-uppercase font-weight-bold"><a href="{{ path('appartementB.show', {slug: appartementB.slug, id: appartementB.id}) }}" target="_blank">{{ appartementB.title }}</a></small>
                      <div class="mb-0">
                        <p class="mb-0">{% if appartementB.available == 0 %}<i class="fas fa-check text-success"></i> <span class="font-weight-bold">Disponible</span>{% else %}<i class="fas fa-times text-danger"></i> <span class="font-weight-bold">Louer</span>{% endif %} | Prix : <span class="font-weight-bold">{{ appartementB.formattedPrice }}</span> <i class="fas fa-euro-sign text-danger"></i></p>
                        <p class="mb-0">{{ appartementB.address }} - {{ appartementB.postalCode}}</p>
                        <p><i class="fas fa-map-marker-alt text-primary"></i> {{ appartementB.city }}</p>
                      </div>
                      <hr>
                      {% endfor %}
                    </div>
                  </div>
                </div>
                
              </div>
            </div>
          </div>
        </div>
    </div>
{% endblock %}